repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0  # This is the latest version as of 14/3/2025
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black