name: FastAPI CI Pipeline
run-name: ${{ github.actor }} is building this FastAPI app ! 🚀

on:
  push:
    branches:
      - main
    paths:
      # only build for source code changes
      - 'src/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # provided by github by default no need to create manually
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "IMAGE_TAG=$(date +'%Y-%m-%d_%H-%M-%S')-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/fastapi-redis:${{ env.IMAGE_TAG }}

      - name: Image details
        run: echo "Docker image has been pushed to ghcr.io/${{ github.repository }}/fastapi-redis:${{ env.IMAGE_TAG }}"